modules.define('welcome',{
    files:['pages/welcome.js']
});

modules.define('hiking',{
    files:['pages/hiking.js']
});
modules.define('members',{
    files:['pages/members.js']
});
modules.define('route',{
    dependensies:['leaflet','leaflet-gpx'],
    files:['pages/route.js']
});
modules.define('points',{
    files:['pages/points.js']
});
modules.define('about',{
    files:['pages/about.js']
});
modules.define('pointsPosition',{
    files:['js/points_position.js']
});
